---
title: "umap"
author: 'Davey1220: <1369852697@qq.com>'
date: "2020/10/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 18. UMAP图绘制

### 清除当前环境中的变量
```{r}
rm(list=ls())
```

### 设置工作目录
```{r}
setwd("C:/Users/Dell/Desktop/R_Plots/18umap/")
```

### 查看示例数据
```{r}
head(iris)

iris.data = iris[,c(1:4)]
iris.labels = iris$Species
head(iris.data)
head(iris.labels)
```

## 使用umap包进行UMAP降维可视化分析
```{r}
library(umap)

# 使用umap函数进行UMAP降维分析
iris.umap = umap::umap(iris.data)
iris.umap

# 查看降维后的结果
head(iris.umap$layout)

# 使用plot函数可视化UMAP的结果
plot(iris.umap$layout,col=iris.labels,pch=16,asp = 1,
     xlab = "UMAP_1",ylab = "UMAP_2",
     main = "A UMAP visualization of the iris dataset")
# 添加分隔线
abline(h=0,v=0,lty=2,col="gray")
# 添加图例
legend("topright",title = "Species",inset = 0.01,
       legend = unique(iris.labels),pch=16,
       col = unique(iris.labels))
```

## 使用uwot包进行UMAP降维可视化分析
```{r}
library(uwot)

head(iris)

# 使用umap函数进行UMAP降维分析
iris_umap <- uwot::umap(iris)
head(iris_umap)

# 使用plot函数可视化UMAP降维的结果
plot(iris_umap,col=iris$Species,pch=16,asp = 1,
     xlab = "UMAP_1",ylab = "UMAP_2",
     main = "A UMAP visualization of the iris dataset")
# 添加分隔线
abline(h=0,v=0,lty=2,col="gray")
# 添加图例
legend("topright",title = "Species",inset = 0.01,
       legend = unique(iris$Species),pch=16,
       col = unique(iris$Species))

# Supervised dimension reduction using the 'Species' factor column
iris_sumap <- uwot::umap(iris, n_neighbors = 15, min_dist = 0.001,
                   y = iris$Species, target_weight = 0.5)
head(iris_sumap)

iris_sumap_res <- data.frame(iris_sumap,Species=iris$Species)
head(iris_sumap_res)

# 使用ggplot2包可视化UMAP降维的结果
library(ggplot2)

ggplot(iris_sumap_res,aes(X1,X2,color=Species)) + 
  geom_point() + theme_bw() + 
  geom_hline(yintercept = 0,lty=2,col="red") + 
  geom_vline(xintercept = 0,lty=2,col="blue",lwd=1) +
  theme(plot.title = element_text(hjust = 0.5)) + 
  labs(x="UMAP_1",y="UMAP_2",
       title = "A UMAP visualization of the iris dataset")
```

```{r}
sessionInfo()
```
